### ISSUE TITLE
Haddock fails to build

### ISSUE THREAD

**Issue by mihaimaruseac** [luispedro/conduit-algorithms#1]
Log below

```haskell
Data/Conduit/Algorithms/Async.hs:17:1: error:
    parse error on input ‘import’
   |
17 | import qualified Data.ByteString as B
   | ^^^^^^
Haddock coverage:
```

**Comment by mihaimaruseac** [comment]
It's still failing on stackage, probably requires a new release?

**Comment by luispedro** [comment]
Just released a new version (0.0.2.0). Hopefully hackage will also be able to build docs.

Thanks for the report, BTW.

**Comment by luispedro** [comment]
Hackage has built the docs successfully.

**Comment by mihaimaruseac** [comment]
Thanks. It should get into nightly soon then.
